services:

  flux-backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_PRETTY=${LOG_PRETTY}
      - REDIS_HOST=${REDIS_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - QDRANT_HTTP_URL=${QDRANT_HTTP_URL}
      - QDRANT_RPC_URL=${QDRANT_RPC_URL}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  flux-worker:
    build: .
    command: ["dist/worker.js"]
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_PRETTY=${LOG_PRETTY}
      - REDIS_HOST=${REDIS_HOST}
      - DATABASE_URL=${DATABASE_URL}
      - QDRANT_HTTP_URL=${QDRANT_HTTP_URL}
      - QDRANT_RPC_URL=${QDRANT_RPC_URL}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_PUBLIC_URL=${S3_PUBLIC_URL}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  vector-db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
  db:
    image: postgres:15
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
    volumes:
    - ./pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes

  s3:
    image: chrislusf/seaweedfs
    ports:
      - "8333:8333"
      - "8888:8888"
      - "9333:9333"
    volumes:
      - ./s3_data:/data
    command: ["server", "-s3", "-s3.allowedOrigins=*", "-ip.bind=0.0.0.0"]
  

volumes:
  qdrant_storage:
  pgdata:
  redis_data:
  s3_data: